//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CottonHarvestDataTransferApp.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecentFile
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Filename { get; set; }
        public System.DateTime DownloadTime { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
